analysis/urls.py
from django.urls import path

from .views import AnalysisHomepage, AnalysisIncomeView, AnalysisOutcomeView, CashRowView, BalanceSheetView, StoreInventoryView

app_name='analysis'

urlpatterns = [
    path('homepage/', AnalysisHomepage.as_view(), name='homepage'),
    path('incomes/', AnalysisIncomeView.as_view(), name='income_analysis'),
    path('outcomes/', AnalysisOutcomeView.as_view(), name='outcome_analysis'),
    path('cash-row/', CashRowView.as_view(), name='cash_row'),
    path('balance-sheet/', BalanceSheetView.as_view(), name='balance_sheet'),
    path('apografi/', StoreInventoryView.as_view(), name='store_inventory')
    
]

myData/urls.py
from django.urls import path, include
from .views import test_get_view

app_name = 'incomes'

urlpatterns = [
    path('', test_get_view, name='home'),

]

shop_quick_view/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('costumers/', include('costumers.urls')),
    path('', include('frontend.urls')),
    path('warehouse/', include('vendors.urls')),
    path('products/', include('products.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('payrolls-and-bills/', include('payroll.urls')),
    path('incomes/', include('incomes.urls')),
    path('analysis/', include('analysis.urls')),
    path('generic-expenses/', include('general_expenses.urls')),
    path('notebook/', include('notebook.urls')),

    path('myData/', include('myData.urls'))
]

analysis/models.py
from django.db import models

# Create your models here.

analysis/views.py
from django.db.models import Sum, FloatField, F
from django.db.models.functions import TruncMonth
from django.shortcuts import  reverse

from django.views.generic import ListView, TemplateView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings


from operator import attrgetter
from itertools import chain

from incomes.models import Income, Costumer, CostumerPayment
from products.models import Product, ProductVendor
from payroll.models import Bill, Payroll
from vendors.models import Payment, Invoice
from general_expenses.models import GeneralExpense
from .tools import sort_months


@method_decorator(staff_member_required, name='dispatch')
class AnalysisHomepage(TemplateView):
    template_name = 'analysis/homepage.html'


@method_decorator(staff_member_required, name='dispatch')
class AnalysisIncomeView(ListView):
    model = Income
    template_name = 'analysis/analysis_incomes.html'
    paginate_by = 100

    def get_queryset(self):
        qs = Income.objects.all()
        qs = Income.filters_data(self.request, qs)
        return qs

    def get_context_data(self,  **kwargs):
        context = super().get_context_data(**kwargs)
        date_filter, currency = True, settings.CURRENCY
        back_url = reverse('analysis:homepage')
        total_value = round(self.object_list.aggregate(Sum('total_value'))['total_value__sum'] if self.object_list.exists() else 0, 2)
        taxes = round(self.object_list.aggregate(Sum('taxes'))['taxes__sum'] if self.object_list.exists() else 0, 2)
        clean_value = round(self.object_list.aggregate(Sum('value'))['value__sum'] if self.object_list.exists() else 0, 2)
        context['costumer_filter'] = True
        context['costumers'] = Costumer.objects.all()
        #     total=Sum('final_value')).values('month', 'total').order_by('month')
        analysis_per_month = self.object_list.annotate(month=TruncMonth('date_expired')).values('month').annotate(
            total=Sum('value')).values('month', 'total').order_by('month')

        analysis_value_per_month = self.object_list.annotate(month=TruncMonth('date_expired')).values('month').annotate(
            total=Sum('value')).values('month', 'total').order_by('month')
        analysis_taxes_per_month = self.object_list.annotate(month=TruncMonth('date_expired')).values('month').annotate(
            total=Sum('taxes')).values('month', 'total').order_by('month')
        analysis_total_value_per_month = self.object_list.annotate(month=TruncMonth('date_expired')).values('month').annotate(
            total=Sum('total_value')).values('month', 'total').order_by('month')
        total_incomes = self.object_list.aggregate(Sum('total_value'))['total_value__sum']

        context.update(locals())
        return context
    

@method_decorator(staff_member_required, name='dispatch')
class AnalysisOutcomeView(TemplateView):
    template_name = 'analysis/analysis_outcome.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        currency = settings.CURRENCY
        back_url = reverse('analysis:homepage')
        date_filter = True

        # grab the data
        bills = Bill.filters_data(self.request, Bill.objects.all())
        payrolls = Payroll.filters_data(self.request, Payroll.objects.all())
        invoices = Invoice.filters_data(self.request, Invoice.objects.all())
        generic_expenses = GeneralExpense.filters_data(self.request, GeneralExpense.objects.all())

        # calculate the total taxes
        total_taxes = 0
        total_taxes += invoices.aggregate(Sum('total_taxes'))['total_taxes__sum'] if invoices.exists() else 0
        total_taxes += generic_expenses.aggregate(Sum('total_taxes'))['total_taxes__sum'] if generic_expenses.exists() else 0
        total_taxes += bills.aggregate(Sum('total_taxes'))['total_taxes__sum'] if bills.exists() else 0

        generic_expenses_analysis = generic_expenses.values('category__title').annotate(total=Sum('value')).order_by('-total')
        generic_expenses_analysis_per_month = generic_expenses.annotate(month=TruncMonth('date')).values('month'). \
            annotate(total=Sum('value')).values('month', 'total').order_by('month')

        total_bills = bills.aggregate(Sum('final_value'))['final_value__sum'] if bills else 0
        analysis_bills = bills.values('category__title').annotate(total=Sum('final_value')).order_by('-total')
        analysis_bills_per_month = bills.annotate(month=TruncMonth('date_expired')).values('month').annotate(
            total=Sum('final_value')).values('month', 'total').order_by('month')

        total_payroll = payrolls.aggregate(Sum('final_value'))['final_value__sum'] if payrolls else 0
        total_invoices = invoices.aggregate(Sum('final_value'))['final_value__sum'] if invoices else 0
        total_generic = generic_expenses.aggregate(Sum('value'))['value__sum'] if generic_expenses else 0
        total_expenses = total_bills + total_payroll + total_invoices + total_generic
        analysis_invoices = invoices.values('vendor__title').annotate(total=Sum('final_value')).order_by('-total')
        analysis_invoices_per_month = invoices.annotate(month=TruncMonth('date')).values('month').annotate(total=Sum('final_value')).values('month', 'total').order_by('month')
        payroll_analysis = payrolls.values('person__title').annotate(total=Sum('final_value')).order_by('-total')
        payroll_analysis_per_month = payrolls.annotate(month=TruncMonth('date_expired')).values('month').\
            annotate(total=Sum('final_value')).values('month', 'total').order_by('month')

        # get unique months
        months = sort_months([analysis_invoices_per_month, analysis_bills_per_month, payroll_analysis_per_month, generic_expenses_analysis_per_month])

        result_per_months = []
        for month in months:
            data = {
                'month': month,
                'total': 0
            }
            # data['invoice'] = ele['total'] for ele in analysis_invoices_per_month if ele['month'] == month else 0
            for ele in analysis_invoices_per_month:
                if ele['month'] == month:
                    data['invoice'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            for ele in analysis_bills_per_month:
                if ele['month'] == month:
                    data['bills'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            for ele in payroll_analysis_per_month:
                if ele['month'] == month:
                    data['payroll'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            for ele in generic_expenses_analysis_per_month:
                if ele['month'] == month:
                    data['generic'] = ele['total']
                    data['total'] = data['total'] + ele['total']
            data['invoice'] = data['invoice'] if 'invoice' in data.keys() else 0
            data['bills'] = data['bills'] if 'bills' in data.keys() else 0
            data['payroll'] = data['payroll'] if 'payroll' in data.keys() else 0
            data['generic'] = data['generic'] if 'generic' in data.keys() else 0
            result_per_months.append(data)

        context.update(locals())
        return context


@method_decorator(staff_member_required, name='dispatch')
class CashRowView(TemplateView):
    template_name = 'analysis/cash_row.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        currency = settings.CURRENCY
        back_url = reverse('analysis:homepage')
        incomes = Income.filters_data(self.request, Income.objects.all()).order_by('date_expired')
        income_clean_value, income_taxes, income_value = 0, 0, 0
        if incomes.exists():
            income_clean_value = incomes.aggregate(Sum('clean_value'))['clean_value__sum']
            income_taxes = incomes.aggregate(Sum('taxes'))['taxes__sum']
            income_value = incomes.aggregate(Sum('final_value'))['final_value__sum']

        total_z = incomes.aggregate(Sum('sum_z'))['sum_z__sum'] if incomes.exists() else 0
        total_pos = incomes.aggregate(Sum('pos'))['pos__sum'] if incomes.exists() else 0
        total_cash = total_z - total_pos
        total_order = incomes.aggregate(Sum('order_cost'))['order_cost__sum'] if incomes.exists() else 0
        total = incomes.aggregate(Sum('value'))['value__sum'] if incomes.exists() else 0

        date_filter = True

        # outcomes
        vendor_payments = Payment.filters_data(self.request, Payment.objects.all())
        vendor_payments_total = vendor_payments.aggregate(Sum('value'))['value__sum'] if vendor_payments.exists() else 0

        payrolls = Payroll.filters_data(self.request, Payroll.objects.filter(is_paid=True))
        payrolls_total = payrolls.aggregate(Sum('final_value'))['final_value__sum'] if payrolls.exists() else 0

        bills = Bill.filters_data(self.request, Bill.objects.filter(is_paid=True))
        bills_total = bills.aggregate(Sum('final_value'))['final_value__sum'] if bills.exists() else 0

        generic_expenses = GeneralExpense.filters_data(self.request, GeneralExpense.objects.filter(is_paid=True))
        generic_expenses_total = generic_expenses.aggregate(Sum('value'))['value__sum'] if generic_expenses.exists() else 0

        total_expenses = vendor_payments_total + bills_total + payrolls_total + generic_expenses_total
        expenses_query = sorted(
                chain(bills, vendor_payments, payrolls, generic_expenses),
                key=attrgetter('report_date'))
        diff = round(total - total_expenses, 2)
        context.update(locals())
        return context


@method_decorator(staff_member_required, name='dispatch')
class BalanceSheetView(TemplateView):
    template_name = 'analysis/balance_sheet.html'

analysis/templates/analysis/analysis_incomes.html
{% extends 'dashboard.html' %}  {% load render_table from django_tables2 %}


{% block content %}
    <div class="content" xmlns="http://www.w3.org/1999/html">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Συνολική Εικόνα  ==> <span style="color: green"> {{ total_incomes }} {{ currency }} </span></h4>
                        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                            Filters
                        </a>
                        <a href="{{ request.path }}" class="btn btn-danger">Καθαρισμος</a>
                        <a href="{{ back_url }}" class="btn btn-warning pull-right">Επιστροφη</a>
                    </div>
                    <div class="card-body">
                        <div class="collapse" id="collapseExample">
                            <form method="get" class="form">
                                 <div class="row">
                                      {% include 'filters/my_filters.html' %}
                                 </div>
                                 <button type="submit" class="btn btn-"><i class="fa fa-save"></i> Αποθηκευση </button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                    <div class='row'>
                        <div class='col-md-4'>
                            <canvas id="totalChart" width="400" height="400"></canvas>
                        </div>
                         <div class='col-md-8' >
                            <canvas id="lineChart" width="400" height="400"></canvas>
                        </div>
                    </div>
                    
                </h4>
                 
                    
              </div>
              <div class="card-body">
                <div class='row'>
                    <div class='col-6'>
                        <h4>Αναλυση ανα μηνα </h4>
                        <table class='table table-bordered'>
                            <thead>
                                <tr>
                                    <th>Ημερομηνια</th>
                                    <th>Κερδη</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ele in analysis_total_value_per_month %}
                                   <tr>
                                        <td>{{ ele.month.month }}/{{ ele.month.year }}</td>
                                        <td>{{ ele.total }} {{ currency }}</td>
                                   </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class='col-6'>
                        <h4>Αναλυση ανα κατηγορια</h4>
                        <table class='table table-bordered'>
                            <thead>
                                <tr>
                                    <th>Ειδος</th>
                                    <th>Κερδη</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td  class="table-info">ΚΑΘΑΡΗ ΑΞΙΑ</td>
                                    <td  class="table-info">{{ clean_value }} </td>
                                </tr>
                                
                                <tr>
                                    <td>ΦΟΡΟΣ</td>
                                    <td class='table-danger'>{{ taxes }}</td>
                                </tr>
                                <tr>
                                    <td class='table-success'>ΣΥΝΟΛΟ</td>
                                    <td class='table-success'>{{ total_value }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col-10">
                        <h4>Δεδομενα</h4>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>ΗΜΕΡΟΜΗΝΙΑ</th>
                                    <th>ΠΕΛΑΤΗΣ</th>
                                    <th>ΚΑΘΑΡΗ</th>
                                    <th>ΦΟΡΟΣ</th>
                                    <th>ΣΥΝΟΛΟ</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for income in object_list %}
                                    <tr>
                                        <td>{{ income.date_expired }}</td>
                                        <td>{{ income.costumer }}</td>
                                        <td>{{ income.tag_value }}</td>
                                        <td>{{ income.tag_taxes }}</td>
                                        <td>{{ income.tag_total_value }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row" id="modal_area">

        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js" integrity="sha256-TQq84xX6vkwR0Qs1qH5ADkP+MvH0W+9E7TdHJsoIQiM=" crossorigin="anonymous"></script>
    <script>
var ctx = document.getElementById('totalChart');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['ΣΥΝΟΛΟ', 'ΦΟΡΟΣ'],
        datasets: [{
            label: '# Σε Ευρω',
            data: [{{ total_value }}, {{ taxes }}],
            backgroundColor: [
                'green',
                'red',
                'red',
                'yellow',
                'purple'
                
            ],
            borderColor: [
                'green',
                'red',
                'red',
                'yellow',
                'purple'

            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>

<script>
var ctx = document.getElementById('lineChart');
var myChart = new Chart(ctx, {
    type: 'line',

    data: {
        labels: [{% for ele in analysis_value_per_month %} {% if forloop.last %} '{{ ele.month }}'{% else %} '{{ele.month}}', {% endif %} {% endfor %}],
        datasets: [
            {
				label: 'ΚΑΘΑΡΑ ΕΣΟΔΑ',
				backgroundColor: 'green',
				borderColor: 'green',
				fill: false,
				data:[{% for ele in analysis_value_per_month %} {% if forloop.last %} {{ ele.total }}{% else %} {{ele.total}}, {% endif %} {% endfor %}],
			},
            {
				label: 'ΑΞΙΑ',
				backgroundColor: 'blue',
				borderColor: 'blue',
				fill: false,
				data:[{% for ele in analysis_total_value_per_month %} {% if forloop.last %} {{ ele.total }}{% else %} {{ele.total}}, {% endif %} {% endfor %}],
			},
            {
				label: 'ΦΟΡΟΣ',
				backgroundColor: 'red',
				borderColor: 'red',
				fill: false,
				data:[{% for ele in analysis_taxes_per_month %} {% if forloop.last %} {{ ele.total }}{% else %} {{ele.total}}, {% endif %} {% endfor %}],
			},
            {
				label: 'Μετρητα',
				backgroundColor: 'yellow',
				borderColor: 'yellow',
				fill: false,
				data:[{% for ele in analysis_cash_per_month %} {% if forloop.last %} {{ ele.total }}{% else %} {{ele.total}}, {% endif %} {% endfor %}],
			}
            ]

		},
    options: {
        maintainAspectRatio: false,
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>
{% endblock %}

analysis/templates/analysis/cash_row.html
{% extends 'dashboard.html' %}  {% load render_table from django_tables2 %}


{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                    <h4>Συνολική Εικόνα ==> <span {% if diff > 0 %} style='color:green' {% else %} style='color:red' {% endif %}> {{diff }} {{ currency }}</span></h4>
                    <p>Κινησεισ Πληρωμων - Εσοδων</p>
                        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                            Filters
                        </a>
                        <a href="{{ request.path }}" class="btn btn-danger">Καθαρισμος</a>
                        <a href="{{ back_url }}" class="btn btn-warning pull-right">Επιστροφη</a>
                    </div>
                    <div class="card-body">
                        <div class="collapse" id="collapseExample">
                            <form method="get" class="form">
                                 <div class="row">
                                      {% include 'filters/my_filters.html' %}
                                 </div>
                                 <button type="submit" class="btn btn-"><i class="fa fa-save"></i> Αποθηκευση </button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                    <div class='row'>
                        <div class='col-md-4'></div>
                         <div class='col-md-8' >
                            {% comment %} <canvas id="lineChart" width="400" height="400"></canvas>  {% endcomment %}
                        </div>
                    </div>
                    
                </h4>
              </div>
              <div class="card-body">
                <div class='row'>
                    <div class='col-md-4'><canvas id="expenseChart" width="500" height="400" style='height:400px'></canvas></div>
                    <div class='col-md-4'></div>
                    <div class='col-md-4'><canvas id="totalChart" width="500" height="400" style='height:400px'></canvas></div>
                </div>
                <div class='row'>
                    <div class='col-md-6'>
                        <h4>Εξοδα Συνολο ==> <span style='color:red'> {{  total_expenses }} {{ currency }}</span></h4>
                        <table class='table table-hover table-bordered'>
                            <thead>
                                <tr class='table-danger'>
                                    <th>Ημερομηνια </th>
                                    <th>Ειδος </th>
                                    <th>Αξια </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ele in expenses_query %}
                                    <tr>
                                        <td>{{ ele.report_date }}</td>
                                        <td>{{ ele.report_expense_type }}</td>
                                        <td class="table-warning">{{ ele.report_value }} {{ currency }}</td>
                                    </tr>
                                {% endfor %}
                            <tbody>
                        </table>
                    </div>
                    <div class='col-md-6'>
                        <h4>Εσοδα ==> Συνολο <span style='color:green'> {{total }} {{ currency }}</span> </h4>
                        
                        <table class='table table-hover table-bordered'>
                            <thead>
                                <tr class='table-success'>
                                    <th class>Ημερομηνια </th>
                                    <th>Ζ Ημερας </th>
                                    <th>Pos Ημερας </th>
                                    <th>Μετρητα </th>  
                                    <th>Τιμολογια </th>
                                    <th>Συνολο </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ele in incomes %}
                                    <tr>
                                        <td>{{ ele.date_expired }}</td>
                                        <td>{{ ele.sum_z }} {{ currency }}</td>
                                        <td>{{ ele.pos }} {{ currency }}</td>
                                        <td>{{ ele.cash }} {{ currency }}</td>
                                        <td>{{ ele.order_cost }} {{ currency }}</td>
                                        <td class="table-success">{{ ele.logistic_value }} {{ currency }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                   
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row" id="modal_area">

        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js" integrity="sha256-TQq84xX6vkwR0Qs1qH5ADkP+MvH0W+9E7TdHJsoIQiM=" crossorigin="anonymous"></script>
    <script>
var ctx = document.getElementById('totalChart');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Συνολο', 'Συνολο Ζ', 'Συνολο POS', 'Mετρητα', 'Συνολο Τιμ.'],
        datasets: [{
            label: '# Σε Ευρω',
            data: [{{ total }}, {{ total_z }}, {{ total_pos }}, {{ total_cash }}, {{ total_order }}],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'green',
                'rgba(153, 102, 255, 0.2)'
                
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)'
                
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
ctx.height = 400;
</script>

<script>
var ctx = document.getElementById('expenseChart');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Συνολικα Εξοδα', 'Πληρωμες Προμηθευτων', 'Λογαριασμοι', 'Μισθοδοσια', 'Γενικά Εξοδα'],
        datasets: [{
            label: '# Σε Ευρω',
            data: [{{ total_expenses }},{{ vendor_payments_total }}, {{ bills_total }}, {{ payrolls_total }}, {{ generic_expenses_total }}],
            backgroundColor: [
                'red',
                'blue',
                'rgba(255, 206, 86, 0.2)',
                'green',
                'rgba(153, 102, 255, 0.2)'
                
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)'
                
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
ctx.height = 400;
</script>

<script>
var ctx = document.getElementById('lineChart');
var myChart = new Chart(ctx, {
    type: 'line',

    data: {
        labels: ['Προμηθευτες', ],
        datasets: [{
				label: 'Προμηθευτες',
				backgroundColor: window.chartColors.red,
				borderColor: window.chartColors.red,
				fill: false,
				data: [
                    {% for ele in analysis_invoices_per_month%}
					randomScalingFactor(),
                    {%endfor%}
					randomScalingFactor(),
					randomScalingFactor(),
					randomScalingFactor(),
					randomScalingFactor(),
					randomScalingFactor(),
					randomScalingFactor()
				],
			}
            ]
    options: {
        maintainAspectRatio: false,
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>
{% endblock %}

analysis/templates/analysis/homepage.html
{% extends 'dashboard.html' %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Εσοδα</h4>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'analysis:income_analysis' %}" class="btn btn-success">Αναλυση Εσοδων</a>
                        {% comment %}<a href="{% url 'analysis:store_inventory' %}" class="btn btn-info pull-right">Απογραφη</a> {% endcomment %}
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Εξοδα</h4>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'analysis:outcome_analysis' %}" class="btn btn-danger">Αναλυση Εξόδων</a>

                    </div>
                </div>
            </div>

            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Ισολογισμος</h4>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'analysis:balance_sheet' %}" class="btn btn-warning">Αναλυση Εσοδων - Εξοδων</a>

                    </div>
                </div>
            </div>
        </div>


    </div>
{% endblock %}