costumers/urls.py
from django.urls import path

from .views import (
    PaymentInvoiceListView, PaymentInvoiceCreateView, PaymentInvoiceUpdateView, print_invoice_view,
                    PaymentInvoiceCreateFromOrderView, check_if_locked_view, delete_payment_invoice,
                    locked_invoice_view,
                    )
from .ajax_views import (ajax_create_item, update_costumer_detail_view, ajax_delete_order_item)
app_name = 'costumers'

urlpatterns = [
    path('home/', PaymentInvoiceListView.as_view(), name='home'),
    path('check-if-locked/', check_if_locked_view, name='check_if_locked'),
    path('payment-invoice-create/', PaymentInvoiceCreateView.as_view(), name='payment_invoice_create'),
    path('payment-invoice-create-from-costumer/<int:pk>', PaymentInvoiceCreateFromOrderView.as_view(),
         name='payment_invoice_create_costumer'),
    path('payment-update/<int:pk>/', PaymentInvoiceUpdateView.as_view(), name='payment_invoice_update'),

    path('ajax/create/<int:pk>/', ajax_create_item, name='ajax_create_item'),
    path('ajax/delete/<int:pk>/', ajax_delete_order_item, name='ajax_delete_order_item'),
    path('print/<int:pk>/', print_invoice_view, name='print_invoice'),
    path('update-invoice-profile/<int:pk>/', update_costumer_detail_view, name='update_invoice_profile'),
    path('payment-invoice-delete/<int:pk>/', delete_payment_invoice, name='delete_payment_invoice'),
    path('lnvoice/locked/<int:pk>', locked_invoice_view, name='invoice_locked')

]

myData/urls.py
from django.urls import path, include
from .views import test_get_view

app_name = 'incomes'

urlpatterns = [
    path('', test_get_view, name='home'),

]

shop_quick_view/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('costumers/', include('costumers.urls')),
    path('', include('frontend.urls')),
    path('warehouse/', include('vendors.urls')),
    path('products/', include('products.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('payrolls-and-bills/', include('payroll.urls')),
    path('incomes/', include('incomes.urls')),
    path('analysis/', include('analysis.urls')),
    path('generic-expenses/', include('general_expenses.urls')),
    path('notebook/', include('notebook.urls')),

    path('myData/', include('myData.urls'))
]

costumers/models.py
from django.db import models
from django.utils import timezone
from django.db.models import Q, Sum
from django.conf import settings
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from django.shortcuts import get_object_or_404

from tinymce.models import HTMLField

from frontend.models import PaymentMethod

from decimal import Decimal
CURRENCY = settings.CURRENCY


class MyCard(models.Model):
    favorite = models.BooleanField(default=False, verbose_name='Προτεινομενο')
    title = models.CharField(unique=True, max_length=200, verbose_name='Τιτλος')
    eponimia = models.CharField(max_length=200, verbose_name='Επωνυμια')
    job = models.TextField(verbose_name='Περιγραφη Επαγγελματος')
    afm = models.CharField(max_length=10, verbose_name='ΑΦΜ')
    doy = models.CharField(max_length=150, verbose_name='ΔΟΥ')
    city = models.CharField(max_length=150, verbose_name='Εδρα')
    zipcode = models.CharField(max_length=10, verbose_name='TK')
    phone = models.CharField(max_length=100, verbose_name='Τηλεφωνα')
    fax = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)

    def __str__(self):
        return self.title


class Costumer(models.Model):
    eponimia = models.CharField(null=True, max_length=240, verbose_name='Επωνυμια')
    address = models.CharField(blank=True, null=True, max_length=240, verbose_name='Διευθυνση')
    job_description = models.CharField(blank=True, null=True, max_length=240, verbose_name='Επαγγελμα')
    loading_place = models.CharField(blank=True, null=True, max_length=240, default='Εδρα μας', verbose_name='Τοπος Φορτωσης')
    destination = models.CharField(blank=True, null=True, max_length=240, default='Εδρα του,', verbose_name='Προορισμος')
    afm = models.CharField(blank=True, null=True, max_length=10, verbose_name='ΑΦΜ')
    doy = models.CharField(blank=True, null=True, max_length=240, default='Σπαρτη', verbose_name='ΔΟΥ')
    destination_city =  models.CharField(blank=True, null=True, max_length=240 , verbose_name='Πολη')
    transport = models.CharField(blank=True, null=True, max_length=10, verbose_name='Μεταφορικο Μεσο')

    first_name = models.CharField(max_length=200, verbose_name='Ονομα', blank=True)
    last_name = models.CharField(max_length=200, verbose_name='Επιθετο', blank=True)
    amka = models.CharField(max_length=20, blank=True, verbose_name='Ψευδονυμο')
    notes = models.CharField(max_length=200, blank=True, verbose_name='Σημειώσεις')
    cellphone = models.CharField(max_length=20, blank=True, verbose_name='Κινητό')
    phone = models.CharField(max_length=20, blank=True, verbose_name='Τηλέφωνο')
    active = models.BooleanField(default=True, verbose_name='Ενεργός')
    value = models.DecimalField(decimal_places=2, max_digits=20, default=0.00)
    paid_value = models.DecimalField(decimal_places=2, max_digits=20, default=0.00)
    balance = models.DecimalField(decimal_places=2, max_digits=20, default=0.00)

    class Meta:
        ordering = ['eponimia', 'afm']

    def save(self, *args, **kwargs):
        self.first_name = self.first_name.capitalize()
        self.last_name = self.last_name.capitalize()
        if not self.eponimia:
            self.eponimia = f'{self.first_name} {self.last_name}'
        self.balance = self.value - self.paid_value
        super(Costumer, self).save(*args, **kwargs)

    def __str__(self):
        return self.eponimia

    def update_orders(self):
        qs = self.orders.all()
        new_value = qs.aggregate(Sum('value'))['value__sum'] if qs.exists() else 0
        self.value = new_value
        self.save()

    def update_payments(self):
        qs = self.payments.all()
        new_value = qs.aggregate(Sum('value'))['value__sum'] if qs.exists() else 0
        self.paid_value = new_value
        self.save()

    def tag_balance(self):
        return f'{self.balance} {CURRENCY}'

    def tag_value(self):
        return f'{self.value} {CURRENCY}'

    def tag_paid_value(self):
        return f'{self.paid_value} {CURRENCY}'

    def phones(self):
        return f'{self.cellphone} {self.phone}'

    def get_edit_url(self):
        return reverse('costumer_detail', kwargs={'pk': self.id})

    def get_order_url(self):
        return reverse('create_order_costumer_view', kwargs={'pk': self.id})

    def get_payment_url(self):
        return reverse('create_payment_costumer_view', kwargs={'pk': self.id})

    def get_quick_view_url(self):
        return reverse('costumer_quick_view', kwargs={'pk': self.id})

    @staticmethod
    def filters_data(request, queryset):
        q = request.GET.get('q', None)
        balance_name = request.GET.get('balance_name', None)
        status_name = request.GET.get('active_name', None)
        queryset = queryset.filter(active=True) if status_name else queryset
        queryset = queryset.filter(balance__gt=Decimal('0.00')) if balance_name else queryset
        queryset = queryset.filter(Q(first_name__startswith=q.capitalize()) |
                                   Q(last_name__startswith=q.capitalize()) |
                                   Q(eponimia__icontains=q) |
                                   Q(amka__icontains=q) |
                                   Q(afm__icontains=q) |
                                   Q(cellphone__icontains=q) |
                                   Q(phone__icontains=q)
                                   ).distinct() if q else queryset
        return queryset


class PaymentInvoice(models.Model):
    SERIES = (
        ('a', 'A'),
        ('b', 'B'),
        ('c', 'Γ')
    )
    TYPE_ = (
        ('a', 'Τιμολογιο'),
        ('b', 'Δελτιο Παραγγελίας'),
        ('c', 'Προπαραγγελία')
    )
    locked = models.BooleanField(default=False, verbose_name="Κλειδωμενο")
    payment_info = models.ForeignKey(PaymentMethod, on_delete=models.PROTECT, null=True, verbose_name='Τρόπος Πληρωμής')
    card_info = models.ForeignKey(MyCard, null=True, on_delete=models.PROTECT, verbose_name='Στάμπα')
    order_type = models.CharField(default='a', max_length=1, choices=TYPE_, verbose_name='Ειδος Παραστατικου')
    costumer = models.ForeignKey(Costumer, on_delete=models.PROTECT, null=True, verbose_name='Πελάτης')
    number = models.IntegerField(blank=True, null=True)
    series = models.CharField(max_length=1, choices=SERIES, verbose_name='Σειρά')
    place = models.CharField(max_length=220, blank=True)
    date = models.DateTimeField(verbose_name='Ημερομηνία', default=timezone.now())

    value = models.DecimalField(decimal_places=2, max_digits=17, default=0.00, verbose_name='Αξια Προ Εκπτωσεως')
    discount_value = models.DecimalField(decimal_places=2, max_digits=17, default=0.00, verbose_name='Εκπτωση')
    clean_value = models.DecimalField(decimal_places=2, max_digits=17, default=0.00, verbose_name='Καθαρη Αξια')
    taxes_value = models.DecimalField(decimal_places=2, max_digits=17, default=0.00, verbose_name='Συνολο ΦΠΑ')

    charges_cost = models.DecimalField(decimal_places=2, max_digits=17, default=0.00, verbose_name='επιβαρυνσεις')
    charges_taxes = models.DecimalField(decimal_places=2, max_digits=17, default=0.00, verbose_name='επιβαρυνσεις ΦΠΑ')

    total_value = models.DecimalField(decimal_places=2, max_digits=17, default=0, verbose_name='Πληρωτεο Ποσο')

    final_value = models.DecimalField(decimal_places=2, max_digits=17, default=0, verbose_name='Τελική Αξία')
    notes = HTMLField(blank=True, null=True)

    def save(self, *args, **kwargs):
        items = self.order_items.all()
        self.value = items.aggregate(Sum('clean_value'))['clean_value__sum'] if items.exists() else 0
        self.discount_value = items.aggregate(Sum('discount_value'))['discount_value__sum'] if items.exists() else 0
        self.clean_value = self.value - self.discount_value
        self.taxes_value = items.aggregate(Sum('taxes_value'))['taxes_value__sum'] if items.exists() else 0
        self.total_value = items.aggregate(Sum('total_value'))['total_value__sum'] if items.exists() else 0
        self.final_value = self.total_value + Decimal(self.charges_cost) + Decimal(self.charges_taxes)
        super().save(*args, **kwargs)

    class Meta:
        unique_together = ['number', 'series', 'order_type']
        ordering = ['-id']

    def __str__(self):
        return f'{self.get_series_display()} | {self.number}'

    def tag_title(self):
        return self.__str__()

    def unique_number(self):
        qs = PaymentInvoice.objects.filter(series=self.series)
        if qs.exists():
            number = qs.count()
            return number
        return 1

    def get_edit_url(self):
        return reverse('costumers:payment_invoice_update', kwargs={'pk': self.id})

    def tag_value(self):
        return str(self.value).replace('.', ',')

    def tag_discount_value(self):
        return str(self.discount_value).replace('.', ',')

    def tag_total_value(self):
        return str(self.total_value).replace('.', ',')

    def tag_clean_value(self):
        return str(self.clean_value).replace('.', ',')

    def tag_taxes_value(self):
        return str(self.taxes_value).replace('.', ',')

    def tag_final_value(self):
        return str(self.final_value).replace('.', ',')

    def tag_charges_cost(self):
        return str(self.charges_cost).replace('.', ',')


class CostumerDetails(models.Model):
    costumer = models.ForeignKey(Costumer, on_delete=models.PROTECT)
    invoice = models.OneToOneField(PaymentInvoice, on_delete=models.CASCADE, related_name='profile')
    eponimia = models.CharField(null=True, max_length=240, verbose_name='Επωνυμια')
    address = models.CharField(blank=True, null=True, max_length=240, verbose_name='Διευθυνση')
    job_description = models.CharField(blank=True, null=True, max_length=240, verbose_name='Επαγγελμα')
    loading_place = models.CharField(blank=True, null=True, max_length=240, default='Εδρα μας',

costumers/forms.py
from django import forms
from .models import Costumer, PaymentInvoice, CostumerDetails, InvoiceItem


class BaseForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CostumerForm(BaseForm, forms.ModelForm):

    class Meta:
        model = Costumer
        fields = ['active', 'eponimia', 'amka', 'cellphone', 'afm', 'doy',
                  'address', 'job_description', 'loading_place', 'destination',
                  'destination_city', 'transport', 'phone', 'notes'
         ]


class PaymentInvoiceForm(BaseForm, forms.ModelForm):
    # date = forms.DateTimeField(required=True, widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
    #                          label='Ημερομηνια')

    class Meta:
        model = PaymentInvoice
        fields = ['date', 'order_type', 'series', 'card_info', 'costumer',
                  'payment_info', 'charges_cost', 'notes'
                  ]

    def clean_date(self):
        date = self.cleaned_data.get('date', '')
        print('date', date)
        return date


class PaymentInvoiceEditForm(PaymentInvoiceForm):
    series = forms.CharField(widget=forms.HiddenInput())
    order_type = forms.CharField(widget=forms.HiddenInput())
    costumer = forms.ModelChoiceField(queryset=Costumer.objects.all(), widget=forms.HiddenInput())


class CostumerDetailsForm(BaseForm, forms.ModelForm):
    costumer = forms.ModelChoiceField(queryset=Costumer.objects.all(), widget=forms.HiddenInput(), required=True)
    invoice = forms.ModelChoiceField(queryset=PaymentInvoice.objects.all(), widget=forms.HiddenInput(), required=True)

    class Meta:
        model = CostumerDetails
        fields = '__all__'


class CreateInvoiceItemForm(BaseForm, forms.ModelForm):
    invoice = forms.ModelChoiceField(queryset=PaymentInvoice.objects.all(), widget=forms.HiddenInput(), required=True)


    class Meta:
        model = InvoiceItem
        fields = ['title', 'unit', 'qty', 'value', 'discount',
                  'taxes_modifier', 'invoice']

costumers/templates/costumers/print/index.html
<!DOCTYPE html> {% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{{ instance.costumer }} | {{ instance.get_series_display }} | {{ instance.number }}</title>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <style>
            .my_card{
                foxnt-size: 10px;
            }
        </style>
<!------ Include the above in your HEAD tag ---------->
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card ">
                        <div class="card-body p-0 my_card">
                            <div class="row p-5">
                                <div class="col-md-6">
                                    <p class="font-weight-bold mb-4">{{ card_info.eponimia }}</p>
                                    <p class="mb-1">{{ card_info.job }}</p>
                                    <p class="mb-1">{{ card_info.city }}</p>
                                    <p class="mb-1">ΑΦΜ: {{ card_info.afm }} ΔΟΥ: {{ card_info.doy }}</p>
                                    <p class="mb-1">ΤΗΛΕΦΩΝΑ: {{ card_info.phone }}</p>
                                </div>

                                <div class="col-md-6 text-right my_card">
                                    <table class="table table-bordered">
                                        <tbody>
                                            <tr>
                                                <th>Είδος Παραστατικού</th>
                                                <th>{{ instance.get_order_type_display }}</th>
                                            </tr>
                                            <tr>
                                                <th>Σειρα - Αριθμός</th>
                                                <th><p class="font-weight-bold mb-1">{{ instance.get_series_display }}-{{ instance.number }}</p></th>
                                            </tr>
                                            <tr>
                                                <th>Ημερομηνια - Ωρα</th>
                                                <th>{{ instance.date|date:"d/m/Y"}} - {{ instance.date|date:"H:m"}}</th>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <hr>
                            <div class="row pb-5 p-5 ">
                                <div class="col-md-6 my_card">
                                    <p class="font-weight-bold mb-4">Πληροφοριες Πελατη</p>
                                    <table class="table table-bordered table-sm">
                                        <tbody>
                                            <tr>
                                                <th>Επωνυμία</th>
                                                <td>{{ costumer.eponimia }}</td>
                                            </tr>
                                            <tr>
                                                <th>Επάγγελμα</th>
                                                <td>{{ costumer.job }}</td>
                                            </tr>
                                            <tr>
                                                <th>Α.Φ.Μ.</th>
                                                <td>{{ costumer.afm }}</td>
                                            </tr>
                                            <tr>
                                                <th>Δ.Ο.Υ</th>
                                                <td>{{ costumer.doy }}</td>
                                            </tr>
                                            <tr>
                                                <th>Διεύθυνση</th>
                                                <td>{{ costumer.address }}</td>
                                            </tr>
                                            <tr>
                                                <th>Πολη - ΤΚ</th>
                                                <td>{{ costumer.city }} {{ card_info.zipcode }}</td>
                                            </tr>
                                            <tr>
                                                <th>Τηλέφωνο</th>
                                                <td>{{ costumer.phone }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    {% comment %}
                                    <p class="mb-1">John Doe, Mrs Emma Downson</p>
                                    <p>Acme Inc</p>
                                    <p class="mb-1">Berlin, Germany</p>
                                    <p class="mb-1">6781 45P</p>
                                    {% endcomment %}
                                </div>

                                <div class="col-md-6 text-right">
                                     <p class="font-weight-bold mb-4">Πληροφοριες Πελατη</p>
                                     <table class="table table-bordered table-sm">
                                        <tbody>
                                            <tr>
                                                <th>Τόπος Αποστολής</th>
                                                <td>{{ costumer.loading_place }}</td>
                                            </tr>
                                            <tr>
                                                <th>Τόπος Προορισμού</th>
                                                <td>{{ costumer.destination_city }}</td>
                                            </tr>
                                            <tr>
                                                <th>Αριθμός Αυτοκινήτου</th>
                                                <td>{{ costumer.afm }}</td>
                                            </tr>
                                            <tr>
                                                <th>Τρόπος Πληρωμής</th>
                                                <td>{{ instance.payment_info }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <h6 class="text-left">Σημειωσεις</h6>
                                    <hr >
                                    <div class="text-left">{{ instance.notes|safe }}</div>

                                </div>
                            </div>

                            <div class="row p-5">
                                <div class="col-md-12">
                                    <table class="table" style="font-size: 16px">
                                        <thead>
                                            <tr>
                                                <th colspan="2" class="border-0 text-uppercase small font-weight-bold">ΠΕΡΙΓΡΑΦΗ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΜΜ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΠΟΣΟΤΗΤΑ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΤΙΜΗ <br> ΜΟΝΑΔΑΣ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΚΑΘΑΡΗ <br>ΑΞΙΑ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΕΚΠΤΩΣΗ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΣΥΝΟΛΙΚΗ<br> ΑΞΙΑ</th>
                                                <th class="border-0 text-uppercase small font-weight-bold">ΦΠΑ %</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for ele in instance.order_items.all %}
                                                <tr>
                                                    <td colspan="2">{{ ele.title }}</td>
                                                    <td>{{ ele.get_unit_display }}</td>
                                                    <td>{{ ele.qty }}</td>
                                                    <td>{{ ele.tag_value }}</td>
                                                    <td>{{ ele.tag_clean_value }}</td>
                                                    <td>{{ ele.tag_discount }} %</td>
                                                    <td>{{ ele.tag_total_value }}</td>
                                                    <td>{{ ele.taxes_modifier }}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            <div class="d-flex flex-row-reverse p-4">
                                <div class="py-2 px-5 text-right">
                                    <div class="mb-2">Τελ.Ποσό</div>
                                    <div class="h2 font-weight-light">{{ instance.tag_final_value }}</div>
                                </div>

                                <div class="py-2 px-5 text-right">
                                    <div class="mb-2">Φ.Π.Α.</div>
                                    <div class="h2 font-weight-light">{{ instance.tag_taxes_value }}</div>
                                </div>
                                <div class="py-2 px-5 text-right">
                                    <div class="mb-2">Καθ. Αξία</div>
                                    <div class="h2 font-weight-light">{{ instance.tag_clean_value }}</div>
                                </div>
                                <div class="py-2 px-5 text-right">
                                    <div class="mb-2">Έκπτωση</div>
                                    <div class="h2 font-weight-light">{{ instance.tag_discount_value }}</div>
                                </div>


                                <div class="py-3 px-5 text-right">
                                    <div class="mb-2">Αξία Προ Έκπ.</div>
                                    <div class="h2 font-weight-light">{{ instance.tag_value }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
  </body>
</html>