incomes/urls.py
from django.urls import path
from .views import (
    IncomeListView, InvoiceCreateView, IncomeUpdateView, income_delete_view,
    CostumerListView, CostumerCreateView, CostumerUpdateView, costumer_delete_view
                    )

from .action_views import (
    validate_payment_creation_view, update_or_delete_payment_from_costumer_view,
    update_or_delete_income_view

)

app_name = 'incomes'

urlpatterns = [
    path('list/', IncomeListView.as_view(), name='list'),
    path('create/', InvoiceCreateView.as_view(), name='create'),
    path('update/<int:pk>/', IncomeUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', income_delete_view, name='delete'),

    path('costumer/list/', CostumerListView.as_view(), name='costumer_list'),
    path('costumers/create/', CostumerCreateView.as_view(), name='costumer_create'),
    path('costumers/update/<int:pk>/', CostumerUpdateView.as_view(), name='costumers_update'),
    path('costumers/delete/<int:pk>', costumer_delete_view, name='costumers_delete'),

    path('action/validate-payment-creation/<int:pk>/', validate_payment_creation_view, name='validate_payment_creation'),
    path('action/update-or-delete-payment-view/<int:pk>/<slug:type_>/', update_or_delete_payment_from_costumer_view,
         name='update_or_delete_payment_view'),
    path('action/validate-income/<int:pk>/<slug:type_>/', update_or_delete_income_view, name='update_or_delete_income_view')



   
]

myData/urls.py
from django.urls import path, include
from .views import test_get_view

app_name = 'incomes'

urlpatterns = [
    path('', test_get_view, name='home'),

]

shop_quick_view/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('costumers/', include('costumers.urls')),
    path('', include('frontend.urls')),
    path('warehouse/', include('vendors.urls')),
    path('products/', include('products.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('payrolls-and-bills/', include('payroll.urls')),
    path('incomes/', include('incomes.urls')),
    path('analysis/', include('analysis.urls')),
    path('generic-expenses/', include('general_expenses.urls')),
    path('notebook/', include('notebook.urls')),

    path('myData/', include('myData.urls'))
]

incomes/models.py
from django.db import models
from django.shortcuts import reverse
from django.db.models import Sum, Q
from django.db.models.signals import post_delete
from django.conf import settings
from django.dispatch import receiver
from vendors.models import TAXES_CHOICES
from django.utils import timezone

from tinymce.models import HTMLField
from decimal import Decimal

from frontend.tools import initial_date
from frontend.models import PaymentMethod


CURRENCY = settings.CURRENCY


class Costumer(models.Model):
    title = models.CharField(null=True, max_length=240, verbose_name='Επωνυμια')
    afm = models.CharField(blank=True, null=True, max_length=10, verbose_name='ΑΦΜ')
    doy = models.CharField(blank=True, null=True, max_length=240, default='Σπαρτη', verbose_name='ΔΟΥ')
    notes = models.CharField(max_length=200, blank=True, verbose_name='Σημειώσεις')
    cellphone = models.CharField(max_length=20, blank=True, verbose_name='Κινητό')
    phone = models.CharField(max_length=20, blank=True, verbose_name='Τηλέφωνο')
    active = models.BooleanField(default=True, verbose_name='Ενεργός')
    value = models.DecimalField(decimal_places=2, max_digits=20, default=0.00)
    paid_value = models.DecimalField(decimal_places=2, max_digits=20, default=0.00)
    balance = models.DecimalField(decimal_places=2, max_digits=20, default=0.00)

    class Meta:
        ordering = ['title', 'afm']

    def save(self, *args, **kwargs):
        incomes = self.incomes.all()
        payments = self.payments.all()
        self.value = incomes.aggregate(Sum('total_value'))['total_value__sum'] if incomes.exists() else 0
        self.paid_value = payments.aggregate(Sum('value'))['value__sum'] if payments.exists() else 0
        self.balance = self.value - self.paid_value
        super(Costumer, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def tag_balance(self):
        return f'{self.balance} {CURRENCY}'

    def tag_value(self):
        return f'{self.value} {CURRENCY}'

    def tag_paid_value(self):
        return f'{self.paid_value} {CURRENCY}'

    def phones(self):
        return f'{self.cellphone} {self.phone}'

    def get_edit_url(self):
        return reverse('incomes:costumers_update', kwargs={'pk': self.id})

    @staticmethod
    def filters_data(request, queryset):
        q = request.GET.get('q', None)
        balance_name = request.GET.get('balance_name', None)
        status_name = request.GET.get('active_name', None)
        queryset = queryset.filter(active=True) if status_name else queryset
        queryset = queryset.filter(balance__gt=Decimal('0.00')) if balance_name else queryset
        queryset = queryset.filter(Q(first_name__startswith=q.capitalize()) |
                                   Q(last_name__startswith=q.capitalize()) |
                                   Q(eponimia__icontains=q) |
                                   Q(amka__icontains=q) |
                                   Q(afm__icontains=q) |
                                   Q(cellphone__icontains=q) |
                                   Q(phone__icontains=q)
                                   ).distinct() if q else queryset
        return queryset


class CostumerPayment(models.Model):
    is_paid = models.BooleanField(default=True, verbose_name='Πληρωμενο')
    timestamp = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(Costumer, on_delete=models.CASCADE, related_name='payments', verbose_name='Πελάτης')
    payment_method = models.ForeignKey(PaymentMethod, null=True, on_delete=models.SET_NULL, verbose_name='Επιταγη')
    date = models.DateField(verbose_name='Ημερομηνία')
    title = models.CharField(max_length=200, blank=True, verbose_name='Τίτλος')
    description = models.TextField(blank=True, verbose_name='Περιγραφή')
    value = models.DecimalField(decimal_places=2, max_digits=20, default=0.00, verbose_name='Ποσό')

    class Meta:
        ordering = ['-date']

    def tag_order_type(self):
        return 'Πληρωμή'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.id:
            self.title = f'Πληρωμή {self.id}' if len(self.title) == 0 else self.title
        super().save(*args, **kwargs)
        self.customer.save()

    def tag_value(self):
        return f'{self.value} {CURRENCY}'

    def tag_final_value(self):
        return self.tag_value()

    def get_edit_url(self):
        return reverse('costumers:payment_update', kwargs={'pk': self.id})

    def get_edit_costumer_url(self):
        return reverse('edit_payment_from_costumer', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('costumers:payment_delete', kwargs={'pk': self.id})

    @staticmethod
    def filters_data(request, qs):
        q = request.GET.get('q', None)
        paid_name = request.GET.getlist('paid_name', None)
        date_start, date_end, date_range = initial_date(request, months=12)
        if q:
            qs = qs.filter(Q(customer__first_name__icontains=q) |
                           Q(customer__last_name__icontains=q) |
                           Q(customer__amka__icontains=q) |
                           Q(customer__cellphone__icontains=q) |
                           Q(customer__phone__icontains=q)
                       ).distinct()
        qs = qs.filter(is_paid=True) if 'have_' in paid_name else qs.filter(is_paid=False) if 'not_' in paid_name else qs
        if date_range:
            qs = qs.filter(date__range=[date_start, date_end])
        return qs


@receiver(post_delete, sender=CostumerPayment)
def update_costumer_payment_value(sender, instance, **kwargs):
    customer = instance.customer
    customer.save()


class Income(models.Model):
    ORDER_TYPE_STATUS = (
        ('a', 'ΤΙΜΟΛΟΓΙΟ'),
        ('b', 'ΑΠΟΔΕΙΞΗ'),
        ('c', 'ΑΛΛΟ')
    )
    payment_method = models.ForeignKey(PaymentMethod, null=True, verbose_name='ΤΡΟΠΟΣ ΠΛΗΡΩΜΗΣ', on_delete=models.SET_NULL)
    costumer = models.ForeignKey(Costumer, on_delete=models.CASCADE, null=True, related_name='incomes', verbose_name='ΠΕΛΑΤΗΣ')
    date_expired = models.DateField(verbose_name='Ημερομηνια')
    title = models.CharField(blank=True, null=True, verbose_name='Σημειωσεις', max_length=240)
    value = models.DecimalField(decimal_places=2, max_digits=20, default=0, verbose_name='ΚΑΘΑΡΗ ΑΞΙΑ')
    taxes_modifier = models.CharField(max_length=1, choices=TAXES_CHOICES, default='a')
    taxes = models.DecimalField(decimal_places=2, max_digits=20, default=0, verbose_name='ΦΟΡΟΣ')
    order_type = models.CharField(default='a', choices=ORDER_TYPE_STATUS, max_length=1, verbose_name='ΕΙΔΟΣ ΠΑΡΑΣΤΑΤΙΚΟΥ')
    total_value = models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ΑΞΙΑ')

    class Meta:
        ordering = ['-date_expired']

    def __str__(self):
        return f'{self.date_expired}'

    def save(self, *args, **kwargs):
        self.taxes = self.total_value * Decimal(self.get_taxes_modifier_display()/100)
        self.value = self.total_value - self.taxes

        super().save(*args, **kwargs)
        self.costumer.save()

    def tag_value(self):
        return f'{self.value} {CURRENCY}'

    def tag_total_value(self):
        return f'{self.total_value} {CURRENCY}'

    def tag_taxes(self):
        return f'{self.taxes} {CURRENCY}'

    def get_edit_url(self):
        return reverse('incomes:update', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('incomes:delete', kwargs={'pk': self.id})

    @staticmethod
    def filters_data(request, qs):
        search_name = request.GET.get('search_name', None)
        date_start, date_end, date_range = initial_date(request, 6)
        qs = qs.filter(notes__icontains=search_name) if search_name else qs
        print(date_start, date_end)
        if date_start and date_end:
            print('her!')
            qs = qs.filter(date_expired__range=[date_start, date_end])
        return qs

incomes/forms.py
from django import forms

from .models import Income, Costumer, CostumerPayment
from vendors.forms import BaseForm


class IncomeForm(BaseForm, forms.ModelForm):
    date_expired = forms.DateField(required=True, widget=forms.DateInput(attrs={'type': 'date'}), label='Ημερομηνια')
    
    class Meta:
        model = Income
        fields = ['date_expired', 'title', 'costumer', 'payment_method', 'total_value', 'taxes_modifier', ]


class CostumerForm(BaseForm, forms.ModelForm):

    class Meta:
        model = Costumer
        fields = ['active', 'title', 'afm', 'doy', 'cellphone', 'phone', 'notes']


class CostumerPaymentForm(BaseForm, forms.ModelForm):
    date = forms.DateField(required=True, widget=forms.DateInput(attrs={'type': 'date'}), label='Ημερομηνια')

    class Meta:
        model = CostumerPayment
        fields = ['is_paid', 'customer', 'date', 'payment_method', 'title', 'description', 'value']


class CostumerPaymentFromCostumerForm(CostumerPaymentForm):
    # costumer = forms.ModelChoiceField(queryset=Costumer.objects.filter(active=True), widget=forms.HiddenInput())
    pass

class InvoiceFormFromCostumer(IncomeForm):
    # costumer = forms.ModelChoiceField(queryset=Income.objects.all(), widget=forms.HiddenInput())
    pass

incomes/views.py
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, TemplateView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from django_tables2 import RequestConfig

from .models import Income, Costumer
from .tables import IncomeTable, CostumerTable
from .forms import IncomeForm, CostumerForm, CostumerPayment, CostumerPaymentFromCostumerForm


@method_decorator(staff_member_required, name='dispatch')
class IncomeListView(ListView):
    template_name = 'incomes/list_view.html'
    model = Income
    paginate_by = 50

    def get_queryset(self):
        qs = Income.objects.all()
        qs = Income.filters_data(self.request, qs)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['queryset_table'] = IncomeTable(self.object_list)
        context['create_url'] = reverse('incomes:create')
        context['date_filter'] = True
        context['search_filter'], context['costumer_filter'] = 2*[True]
        context['costumers'] = Costumer.objects.all()
        return context


@method_decorator(staff_member_required, name='dispatch')
class InvoiceCreateView(CreateView):
    template_name = 'incomes/form_view.html'
    model = Income
    form_class = IncomeForm
    success_url = reverse_lazy('incomes:list')

    def get_initial(self):
        initial = super().get_initial()
        initial['sum_z'] = 0
        initial['pos'] = 0
        initial['order_cost'] = 0
        initial['extra'] = 0
        initial['sum_z'] = 0
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["back_url"] = self.success_url
        context['form_title'] = "Δημιουργια Εσοδου" 
        return context
    
    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Νεο εσοδο δημιουργηθηκε.')
        return super().form_valid(form)


@method_decorator(staff_member_required, name='dispatch')
class IncomeUpdateView(UpdateView):
    model = Income
    form_class = IncomeForm
    template_name = 'incomes/form_view.html'
    success_url = reverse_lazy('incomes:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['back_url'] = self.success_url
        context['delete_url'] = self.object.get_delete_url()
        context['form_title'] = f'Επεξεργασια {self.object}'
        return context

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'το Εσοδο Ανανεωθηκε')
        return super().form_valid(form)


@staff_member_required
def income_delete_view(request, pk):
    instance = get_object_or_404(Income, id=pk)
    instance.delete()
    messages.warning(request, 'το Εσοδο διαγραφηκε.')
    return redirect(reverse('incomes:list'))


@method_decorator(staff_member_required, name='dispatch')
class CostumerListView(ListView):
    model = Costumer
    template_name = 'list_view.html'
    paginate_by = 50

    def get_queryset(self):
        return Costumer.filters_data(self.request, Costumer.objects.all())

    def get_context_data(self, **kwargs):
        context = super(CostumerListView, self).get_context_data(**kwargs)
        context['create_url'] = reverse('incomes:costumer_create')
        qs_table = CostumerTable(self.object_list)
        RequestConfig(self.request, {'per_page': self.paginate_by}).configure(qs_table)
        context['queryset_table'] = qs_table

        return context


@method_decorator(staff_member_required, name='dispatch')
class CostumerCreateView(CreateView):
    model = Costumer
    template_name = 'form_view.html'
    form_class = CostumerForm

    def get_success_url(self):
        return self.obj.get_edit_url()

    def form_valid(self, form):
        self.obj = form.save()
        return super(CostumerCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CostumerCreateView, self).get_context_data(**kwargs)
        context['back_url'] = reverse('incomes:costumer_list')
        context['form_title'] = 'ΔΗΜΙΟΥΡΓΙΑ ΠΕΛΑΤΗ'
        # context['incomes'] = Income.filters_data(self.request, self.object.incomes.all())
        # context['payments'] = CostumerPayment.filters_data(self.request, self.object.payments.all())
        return context


@method_decorator(staff_member_required, name='dispatch')
class CostumerUpdateView(UpdateView):
    form_class = CostumerForm
    template_name = 'incomes/costumer_card.html'
    model = Costumer

    def get_success_url(self):
        return self.object.get_edit_url()

    def form_valid(self, form):
        form.save()
        return super(CostumerUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CostumerUpdateView, self).get_context_data(**kwargs)
        context['payment_form'] = CostumerPaymentFromCostumerForm(self.request.POST or None, initial={
            'customer': self.object
        })
        context['date_filter'] = True
        context['incomes'] = Income.filters_data(self.request, self.object.incomes.all())
        context['payments'] = CostumerPayment.filters_data(self.request, self.object.payments.all())
        return context


@staff_member_required
def costumer_delete_view(request, pk):
    obj = get_object_or_404(Costumer, id=pk)
    try:
        obj.delete()
    except:
        messages.warning(request, 'ΔΕ ΜΠΟΡΕΙ ΝΑ ΔΙΑΓΡΑΦΕΙ Ο ΥΠΑΡΧΩΝ ΠΕΛΑΤΗΣ')

incomes/templates/incomes/costumer_card.html
{% extends 'dashboard.html' %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="header">
                    <h4>{{ object }} ΥΠΟΛΟΙΠΟ ==> {{ object.tag_balance }}</h4>
                    <a href="{% url 'costumer_list' %}" class="btn btn-warning pull-right">ΕΠΙΣΤΡΟΦΗ</a>
                </div>
            </div>
            </div>

        </div>
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4>ΕΠΕΞΕΡΓΑΣΙΑ {{ object}}</h4>
                        <form class="form" method="post">
                            {% csrf_token %}
                            {{ form }}
                            <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> ΑΠΟΘΗΚΕΥΣΗ </button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h6>ΔΗΜΙΟΥΡΓΙA ΠΛΗΡΩΜΗΣ</h6>
                        <form method="post" class="form" action="{% url 'incomes:validate_payment_creation' object.id %}">
                            {% csrf_token %}
                            {{ payment_form }}
                            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> ΑΠΟΘΗΚΕΥΣΗ </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                            Filters
                        </a>
                        <a href="{{ request.path }}" class="btn btn-danger">Καθαρισμος</a>

                    </div>
                    <div class="card-body">
                        <div class="collapse" id="collapseExample">
                            <form method="get" class="form">
                                 <div class="row">
                                      {% include 'filters/my_filters.html' %}
                                 </div>
                                 <button type="submit" class="btn btn-"><i class="fa fa-save"></i> Αποθηκευση </button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
           <div class="col-6">
               <div class="card">
                   <div class="card-header"><h6>ΤΙΜΟΛΟΓΙΑ</h6></div>
                   <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>ΗΜΕΡΟΜΗΝΙΑ</th>
                                    <th>ΣΧΟΛΙΑ</th>
                                    <th>ΤΡΟΠΟΣ ΠΛΗΡΩΜΗΣ</th>
                                    <th>ΠΟΣΟ</th>
                                    <th>-</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ele in incomes %}
                                    <tr>
                                        <td>{{ ele.date_expired }}</td>
                                        <td>{{ ele.title }}</td>
                                        <td>{{ ele.payment_method }}</td>
                                        <td>{{ ele.tag_total_value }}</td>
                                        <td>
                                            <a href="{% url 'incomes:update_or_delete_income_view' ele.id 'update' %}" class="btn btn-success"><i class="fa fa-edit"></i> </a>
                                            <a href="{% url 'incomes:update_or_delete_income_view' ele.id 'delete' %}" class="btn btn-danger">
                                                <i class="fa fa-remove"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                   </div>
               </div>
           </div>
            <div class="col-6">
               <div class="card">
                   <div class="card-header"><h6>ΠΛΗΡΩΜΕΣ</h6></div>
                   <div class="card-body">
                       <table class="table table-bordered">
                           <thead>
                                <tr>
                                    <th>ΗΜΕΡΟΜΗΝΙΑ</th>
                                    <th>ΣΧΟΛΙΑ</th>
                                    <th>ΤΡΟΠΟΣ ΠΛΗΡΩΜΗΣ</th>
                                    <th>ΠΟΣΟ</th>
                                    <th>- </th>
                                </tr>
                           </thead>
                           <tbody>
                                {% for ele in payments %}
                                    <tr>
                                        <td>{{ ele.date }}</td>
                                        <td>{{ ele.title }}</td>
                                        <td>{{ ele.payment_method }}</td>
                                        <td>{{ ele.tag_final_value }}</td>
                                        <td><a href="{% url 'incomes:update_or_delete_payment_view' ele.id 'update' %}" class="btn btn-primary">
                                            <i class="fa fa-edit"></i> </a>
                                            <a href="{% url 'incomes:update_or_delete_payment_view' ele.id 'delete' %}" class="btn btn-danger">
                                            <i class="fa fa-remove"></i> </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                           </tbody>
                       </table>
                   </div>
               </div>
           </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}

    <script type="text/javascript">
        $('.edit_button').click(function (evt) {
            evt.preventDefault();
            const btn = $(this);
            const url = btn.attr('data-href');
            

        })
    </script>
{% endblock %}

incomes/templates/incomes/form_view.html
{% extends 'dashboard.html' %} {% load static %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-md-8 col-lg-8">
            <div class="card card-user">
              <div class="card-header">
                <h5 class="card-title">{{ form_title }}</h5>
              </div>
              <div class="card-body">
                  <form method="post"> {% csrf_token %}
                      {{ form }}
                      <div class="row">
                          <div class="update ml-auto mr-auto">
                              <button type="submit" class="btn btn-primary btn-round"><i class="fa fa-save"></i>
                                   Αποθηκευση
                              </button>
                              {% if add_button %} <button name="add_button" value="works" class="btn btn-success btn-round">{{ button_title }}</button> {% endif %}
                          </div>
                  </div>
                </form>
              </div>
            </div>
                </div>
            <div class="col-md-4 col-lg-4">
            <div class="card card-user">
              <div class="card-header">
                <a href="{{ back_url }}" class="btn btn-warning">Επιστροφη</a>
                  <br>
                  {% if customer_url %}
                    <a href="{{ customer_url }}" class="btn btn-info">Καρτελα Πελατη</a>
                  {% endif %}
                  <br> <br>  <br> <br>
                  {% if delete_url %}
                    <a href="{{ delete_url }}" onclick="return confirm('Εισαι σιγουρος;')" class="btn btn-danger">Διαγραφη</a>
                  {% endif %}

                  
              </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{ form.media }}
{% endblock %}

incomes/templates/incomes/list_view.html
{% extends 'dashboard.html' %}  {% load render_table from django_tables2 %}


{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                            Filters
                        </a>
                        <a href="{{ request.path }}" class="btn btn-danger">Καθαρισμος</a>
                        
                    </div>
                    <div class="card-body">
                        <div class="collapse" id="collapseExample">
                            <form method="get" class="form">
                                 <div class="row">
                                      {% include 'filters/my_filters.html' %}
                                 </div>
                                 <button type="submit" class="btn btn-"><i class="fa fa-save"></i> Αποθηκευση </button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title"> {{ table_title }}</h4>
                  <a href="{{ create_url }}" class="btn btn-success btn-round btn-move-right">Δημιουργια</a>
                    {% if extra_buttons %}
                        <a href="{% url 'print_list' %}" target="_blank" class="btn btn-info pull-right "><i class="fa fa-print"> </i></a>
                        <button data-href="{% url 'ajax_calculate_balance' %}" class='btn btn-primary pull-right calculate_button'>Υπολογισμος</button>

                    {% endif %}
                    {% if report_button %}
                        <button data-href="{{ report_url }}" class='btn btn-primary pull-right report_button'>Report</button>
                    {% endif %}
              </div>
              <div class="card-body">
                <div class="table-responsive">
                    {% render_table queryset_table %}
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row" id="modal_area">

        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script>
        $('.quick_view').click(function (evt) {
            evt.preventDefault();
            $('#modal_area').empty();
            const my_btn = $(this);
            const url = my_btn.attr('data-href');
            $.ajax({
                method: 'GET',
                dataType: 'json',
                url: url,

                success: function (data) {
                    $('#modal_area').html(data.result);
                    $('#quick_view_modal').modal('show');
                }
        })
        })
    </script>

    <script>
      $('.calculate_button').click(function (evt) {
        evt.preventDefault();
            $('#modal_area').empty();
            const my_btn = $(this);
            const url = my_btn.attr('data-href');
            $.ajax({
                method: 'GET',
                dataType: 'json',
                url: url,

                success: function (data) {
                    $('#modal_area').html(data.result);
                    $('#quick_view_modal').modal('show');
                }
        })
        });

        $('.report_button').click(function(evt){
          evt.preventDefault();
          $('#modal_area').empty();
          const myBtn = $(this);
          const url = myBtn.attr('data-href');
          $.ajax({
            method: 'GET',
            dataType: 'json',
            url: url,

            success: function(data){
              $('#modal_area').html(data.result);
              $('#quick_view_modal').modal('show');
            }
          })
        })
    </script>


{% endblock %}